"""create users and online_users tables

Revision ID: 010738ca3190
Revises: 
Create Date: 2026-07-28 15:47:42.220120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '010738ca3190'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('online_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('ipaddress', sa.String(length=45), nullable=False),
    sa.Column('logindatetime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('firstname', sa.String(length=80), nullable=False),
    sa.Column('middlename', sa.String(length=80), nullable=True),
    sa.Column('lastname', sa.String(length=80), nullable=False),
    sa.Column('birthdate', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('online_users')
    # ### end Alembic commands ###
